project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "CSC 222 Systems Programming"
  site-url: https://csc222.jcor.dev
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - section: "0 - Housekeeping"
        contents: 
          - 00 Housekeeping/01 Syllabus.qmd

      - section: "1 - Linux"
        contents:
          - 01 Linux/01 A Brief History.qmd
          - section: "VM Install"
            contents: 
              - 01 Linux/02 VM Install/01 Overview.qmd
              - 01 Linux/02 VM Install/02 Virtualization Software Install.qmd
              - 01 Linux/02 VM Install/03 Download an Image.qmd
              - 01 Linux/02 VM Install/04 Creating the VM.qmd
              - 01 Linux/02 VM Install/05 Installing the VM.qmd
              - 01 Linux/02 VM Install/06 Creating a Shared Folder.qmd
              - 01 Linux/02 VM Install/07 Installing Tools on VM.qmd
          - 01 Linux/linux-filesystem.qmd
          # - linux/vm-install-win.qmd
          # - linux/vm-install-mac.qmd
          # - linux/additional-steps.qmd


      - section: "2 - Terminal"
        href: 02 Terminal/
        contents:
          - 02 Terminal/00 Background.qmd
          - 02 Terminal/01 Basic Commands.qmd
          - 02 Terminal/02 Working With Files.qmd
          - 02 Terminal/03 Other Useful Tips.qmd
          - 02 Terminal/04 Redirection.qmd
          - 02 Terminal/05 File Permissions.qmd
          - 02 Terminal/06 Grep and Regex.qmd


      - section: "3 - C Programming"
        contents:
          - 03 C Programming/01-HelloWorld.qmd
          - 03 C Programming/02-DataTypes.qmd
          - 03 C Programming/03-Operators.qmd
          - 03 C Programming/04-Functions.qmd
          - 03 C Programming/05-More-on-Data.qmd
          - 03 C Programming/06-Sample-Applications.qmd
          - 03 C Programming/07-Memory-Allocation.qm4
          - 03 C Programming/08-Structs-and-Unions.qmd
          - 03 C Programming/09-Sample-Applications.qmd
          - 03 C Programming/10-Files.qmd
          - 03 C Programming/11-Fork.qmd
          - 03 C Programming/12-Piping.qmd
          - 03 C Programming/13-Exec-Functions.qmd

      - section: "4 - Computing Systems and Data Representation"
        contents: 
          - 04 Computing Systems and Data Representation/01 Computing Systems.qmd
          - 04 Computing Systems and Data Representation/02 The Compilation Process.qmd
          - 04 Computing Systems and Data Representation/03 Representing Programs.qmd
          - 04 Computing Systems and Data Representation/04 Representing Numeric Data.qmd
          - 04 Computing Systems and Data Representation/05 Byte Ordering Conventions.qmd


      - section: "5 - System Calls"
        contents:
          - ""

      - section: "6 - Bash Scripting"
        contents:
          - 06 Bash Scripting/01-Intro.qmd
          - 06 Bash Scripting/02-Args.qmd
          - 06 Bash Scripting/03-Conditionals.qmd
          - 06 Bash Scripting/04-Exit-Codes.qmd
          - 06 Bash Scripting/05-Case.qmd
          - 06 Bash Scripting/06-Loops.qmd
          - 06 Bash Scripting/07-Functions.qmd

      - section: "7 Assembly Primer"
        contents:
          - 07 Assembly Primer/01 Register Names.qmd
          - 07 Assembly Primer/02 Register Conventions.qmd
          - 07 Assembly Primer/03 Interpreting Operands.qmd
          - 07 Assembly Primer/04 Accessing Values with Operands.qmd
          - 07 Assembly Primer/05 The Move Instruction.qmd
          - 07 Assembly Primer/06 The Load Effective Address Instruction.qmd
          - 07 Assembly Primer/07 Status Flags.qmd
          - 07 Assembly Primer/08 Arithmetic Instructions.qmd
          - 07 Assembly Primer/09 Comparing and Jumps.qmd
          - 07 Assembly Primer/10 Reverse Engineering with C.qmd





format:
  html:
    theme: 
      dark: darkly
      light: cosmo
    css: styles.css
    toc: true
    googlefonts: false



